d <- read.csv("household_power_consumption.txt", header = FALSE, sep = ";", nrows = 2880, skip = 66637)
colnames(d) = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Globa_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
a <- seq(as.POSIXct("2007/2/1"), as.POSIXct("2007/2/3"), "mins")
png(filename = "plot4.png")
par(mfrow = c(2,2))
plot(a[1:2880], d$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(a[1:2880], d$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(a[1:2880], d$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(a[1:2880], d$Sub_metering_2, col = "red")
lines(a[1:2880], d$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1), col = c("black", "red" , "blue"), bty = "n", cex = .5)
plot(a[1:2880], d$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()