d <- read.csv("household_power_consumption.txt", header = FALSE, sep = ";", nrows = 2880, skip = 66637)
colnames(d) = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Globa_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
png(filename = "plot1.png")
hist(d$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()